### ISSUE TITLE
async init

### ISSUE THREAD

**Issue by JohnLindahlTech** [ccorcos/reduxish#1]
Hello
I really like your demo-app and I am trying to reuse a lot of the code in my project. What I am struggling with though, is that I try to adapt it to work with an async version of init-functions but I just don't get it to work, preferably reusing the actions themselves.
e.g: fetching some weather data already in the init-function in the https://github.com/ccorcos/reduxish/blob/master/src/Weather.js

My target is to be able to use the static init function(s) to be able to fetch data on the server before server side rendering and then just passed the hydrated state to the SSR. While at the same time not have to repeat the data-fetching code, once specifically for SSR and one for client-mounted components.

**Comment by ccorcos** [comment]
I would recommend using another approach that I'm working on here: https://github.com/ccorcos/arbol

The problem right now is that only rendering is declarative. With Arbol, I've made all side-effects declarative so SSR with prefetching should be no problem!

**Comment by ccorcos** [comment]
The thing with async init functions is then every init function has to be async and use Promise.all to merge them...

**Comment by JohnLindahlTech** [comment]
Thank you for quick replies!
Will take a proper look at this in the morning, I sat up way to late messing about with this prior to posting this issue.

**Comment by ccorcos** [comment]
haha no worries. I'm happy someone has a similar level of discontent with the status quo for frontend architecture. :) happy to help.

**Comment by JohnLindahlTech** [comment]
Thank you for your input!
Arbol does absolutely look interesting but not in a state to tilt the architecture in such a way.
Ended up rethinking some problems with [reselect](https://github.com/reactjs/reselect)
